In [1]:
import numpy as np

In [2]:
X = 2 * np.random.rand(100,1)
y = 4 + 3 * X + np.random.rand(100,1)
X_b = np.c_[np.ones((100,1)), X]

In [3]:
X_norm = (X - X.mean(axis=0)) / X.std(axis=0)

In [6]:
print(X_norm[:10])

[[ 1.1314985 ]
 [-0.92748555]
 [ 0.09521421]
 [-0.5346998 ]
 [-1.15355031]
 [ 1.38564519]
 [ 1.39565509]
 [ 0.4237178 ]
 [-0.8932757 ]
 [ 0.4220755 ]]


In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_Norm = scaler.fit_transform(X)

In [9]:
print(X_norm[:10])

[[ 1.1314985 ]
 [-0.92748555]
 [ 0.09521421]
 [-0.5346998 ]
 [-1.15355031]
 [ 1.38564519]
 [ 1.39565509]
 [ 0.4237178 ]
 [-0.8932757 ]
 [ 0.4220755 ]]


In [11]:
eta = 0.1
n_iterations = 1000
m = len(X)

In [12]:
theta = np.random.rand(2,1)

In [13]:
for iteration in range(n_iterations):
    gradients = 2 / m * X_b.T.dot(X_b.dot(theta) - y)
    theta = theta - eta * gradients

In [14]:
print(theta)

[[4.56833907]
 [2.96260488]]


In [15]:
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
print(theta_best)

[[4.56833907]
 [2.96260488]]


In [22]:
n_epochs = 50
t0, t1 = 5, 50

def learning_schedule(t):
    return t0 / (t + t1)

theta = np.random.rand(2, 1)

for epoch in range(n_epochs):
    for i in range(m):
        random_index = np.random.randint(m)
        xi = X_b[random_index:random_index+1]
        yi = y[random_index:random_index+1]
        gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
        eta = learning_schedule(epoch * m + i)
        theta = theta - eta * gradients

print(theta)

[[4.56130844]
 [2.96553593]]


In [27]:
from sklearn.linear_model import SGDRegressor
sgd_reg=SGDRegressor(n_iter=50, penalty=None, eta0=0.1)
sgd_reg.fit(X, y.ravel())

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
       eta0=0.1, fit_intercept=True, l1_ratio=0.15,
       learning_rate='invscaling', loss='squared_loss', max_iter=None,
       n_iter=50, n_iter_no_change=5, penalty=None, power_t=0.25,
       random_state=None, shuffle=True, tol=None, validation_fraction=0.1,
       verbose=0, warm_start=False)

In [28]:
sgd_reg.intercept_, sgd_reg.coef_

(array([4.5795252]), array([2.97558586]))